version: "3"
services: 
  api-backend: 
    build: 
      context: ..
      dockerfile: Dockerfile
    env_file:
      - variables.env
    ports: 
      - 3000:3000
    volumes:
      - "../cmd:/go/src/app/cmd"
      - "../go.mod:/go/src/app/go.mod"
    command: 
      "./main"
    depends_on:
      - postgres
  postgres: 
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432' 
    volumes: 
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local