version: "3"
services: 
  api-backend: 
    build: 
      context: ..
      dockerfile: ./api-backend/Dockerfile
    env_file:
      - variables.env
    ports: 
      - 3000:3000
    command: bash -c "./api-backend/api-backend.bin"
    volumes:
      - .:/app
  db: 
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432' 
    volumes: 
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local